// Server-only content: never serve this file or serialize the full definitions.
const make = (id, title, short, company, brief, fields, options, profiles, rubric) => ({id,title,short,company,brief,fields,options,profiles,rubric});
export const modules = [
make('blueprint','Service blueprint','Connect the customer journey to the work behind it.','Velo · urban mobility',
'Riders see “driver arriving”, yet completed trips have fallen. Operations wants a new dispatch screen. Map the passenger and driver journeys before committing the team.',
['Customer actions and physical evidence','Frontstage touchpoints','Backstage services and supporting processes','Handoffs, failure points and accountable owners'],
['Redesign the rider status screen','Add a driver acceptance handshake and timeout recovery','Expand the driver incentive program'],[
{key:1,source:'trace',truth:'Dispatch marks a trip as assigned before the driver acknowledges it. On weak connections, 18% of assignments never reach the driver.',data:'Funnel: request 100% → assigned 92% → driver acknowledged 74% → pickup 69%.',people:'A driver: “I only saw the booking after the rider called.” Riders cannot distinguish assignment from acceptance.',trace:'10:02 assigned; 10:02 rider notified; 10:03 push timeout; no driver ACK; trip remains assigned.',constraint:'Two engineers, one sprint. Existing push provider supports acknowledgement callbacks.',risk:'The next field trial loses push connectivity for 90 seconds.',response:0},
{key:2,source:'analytics',truth:'Acknowledgements are reliable. The main loss occurs before assignment because available driver supply collapses at the evening peak.',data:'Off-peak: 96% matched. Peak: 61% matched. ACK success among matched trips: 99.7%.',people:'Drivers leave the service at 6 pm for a competitor with a guaranteed minimum. Riders report long waits.',trace:'Assignment → ACK median 210ms, p99 600ms. Unmatched requests time out after 4 minutes.',constraint:'A two-week incentive trial fits the budget; recruitment takes two months.',risk:'Incentives improve supply but margin per ride drops by 12%.',response:1}],
['Map rider and driver separately, including failed journeys.','Distinguish visible promises from backstage state.','Name an owner and recovery behavior for each fragile handoff.']),
make('architecture','Product architecture','Choose service boundaries that match real constraints.','Parcel · local delivery',
'A delivery startup expects growth and the CTO proposes splitting the platform into eight services. Decide the first architectural move and show ownership, storage and dependencies.',
['Components and responsibilities','Data ownership and integration boundaries','Synchronous and asynchronous flow','Scaling bottleneck, failure isolation and tradeoffs'],
['Keep a modular monolith and optimize the database','Extract dispatch behind a queue','Split all domains into independent microservices'],[
{key:0,source:'trace',truth:'The bottleneck is one unindexed order-history query. No domain needs independent scaling yet.',data:'Peak 60 requests/s; DB CPU 91%; app CPU 18%; order history p95 2.4s.',people:'Four engineers share the on-call rotation. A service mesh would have no dedicated owner.',trace:'EXPLAIN order_history: full table scan. Dispatch consumes 4% of CPU.',constraint:'Four engineers and six weeks of runway for this project.',risk:'An index reduces query latency but a reporting job now contends for connections.',response:0},
{key:1,source:'analytics',truth:'Dispatch workloads burst 40× at restaurant closing and starve unrelated requests. An isolated queue addresses the measured failure.',data:'Dispatch queue 18,000 jobs at 22:00; checkout p99 7s during bursts; DB CPU 35%.',people:'A dedicated dispatch team can own the worker and its runbook.',trace:'CPU profiles: route solver 87% of app CPU during bursts. Queries are indexed.',constraint:'Six engineers; a managed queue is already approved.',risk:'The queue protects checkout, but old jobs produce stale assignments.',response:0}],
['Show users, services, stores and external dependencies.','Tie the architectural boundary to measured load and team ownership.','Specify retries, dead-letter handling and rollback.']),
make('apis','Product APIs','Specify contracts and reason through failure paths.','Velo Pay · checkout',
'Support reports confusing payment outcomes. Define the payment API and a request sequence. The team needs your recommendation on what to fix first.',
['Endpoint, GET/POST semantics and request schema','Response, status codes and authentication','Sequence: client → service → provider → callback','Retries, idempotency and compatibility'],
['Use idempotency keys with durable result lookup','Introduce explicit pending status and reconciliation','Retry every failed request immediately'],[
{key:0,source:'trace',truth:'A timeout after capture causes clients to create a second charge with a new request ID.',data:'0.8% of checkouts create two captures. Timeouts correlate with duplicates.',people:'Support sees two receipts for a single order. The first charge often succeeds.',trace:'POST charge accepted → response lost → retry with new key → second capture.',constraint:'Provider supports idempotency keys for 24 hours; mobile can retain the key.',risk:'A callback is delivered twice and out of order.',response:0},
{key:1,source:'trace',truth:'Requests are already idempotent. Delayed callbacks leave successful captures displayed as failed.',data:'Duplicate captures 0.00%; 6% of orders display failure before callback arrives.',people:'Customers are refunded manually even though their order is still pending.',trace:'Key reused correctly. Capture succeeded; webhook delayed 120s; UI treats pending as failure.',constraint:'Provider has a GET status endpoint and signed webhooks.',risk:'The provider status API is unavailable for ten minutes.',response:0}],
['Define authorization separately from authentication.','Handle timeouts as unknown outcomes, not automatic failure.','Document a sequence that includes duplicate and delayed messages.']),
make('stack','Tech stack','Balance platform capabilities, skills and delivery time.','Parcel · courier experience',
'The courier product needs location updates and a new customer ordering flow. Recommend a stack that the team can actually ship and maintain.',
['Web/mobile frontend and device requirements','Backend, database, cache and queue choices','Build versus buy and team capabilities','API call example and operational costs'],
['Responsive web/PWA with the existing backend','Native courier shell with shared web customer experience','Rewrite every client and service in a new language'],[
{key:1,source:'support',truth:'Couriers need reliable background GPS and offline scan storage during locked-screen shifts.',data:'35% of courier events occur while the device is locked; 14% occur offline.',people:'Couriers lock their phones between stops. The team has two mobile engineers.',trace:'Browser location reporting stops after background suspension on target devices.',constraint:'Customer ordering is web-friendly; only the courier workflow needs native capabilities.',risk:'Offline events arrive after the courier has been reassigned.',response:0},
{key:0,source:'support',truth:'This pilot uses staffed kiosks with reliable connectivity, not background courier tracking.',data:'98% of pilot sessions are on managed tablets with continuous Wi-Fi.',people:'All six engineers know the current web stack. Staff use the app in the foreground.',trace:'No background device APIs are required by the pilot acceptance criteria.',constraint:'Three-week pilot deadline; native app review adds schedule risk.',risk:'One pilot location loses connectivity for an hour.',response:0}],
['Separate frontend, backend and infrastructure decisions.','Make the smallest platform commitment that supports required capabilities.','Show an executable-style GET or POST example with externalized credentials.']),
make('metrics','Monitoring & metric trees','Connect customer outcomes to measurable system health.','Velo · growth and health',
'Bookings are rising while rider satisfaction declines. Build a metric tree and choose the first diagnostic metric to put in the operating review.',
['North-star outcome and direct drivers','Proxy metrics and balancing guardrails','SLI numerator, denominator and measurement point','Segments, windows, instrumentation and alerts'],
['Track completed rides per eligible request by cohort','Focus on app downloads and total bookings','Track successful fast responses for the booking journey'],[
{key:0,source:'analytics',truth:'A promotion attracts low-intent bookings and driver cancellations hide behind headline growth. Technical latency is stable.',data:'Bookings +24%; completed rides +2%; promo cohort cancellation 29% vs baseline 6%; p95 320ms.',people:'Operations celebrates bookings, but drivers spend more time on trips that cancel.',trace:'Booking API success 99.96%; no latency regression.',constraint:'Analytics can join request IDs to trip completion within one day.',risk:'Completion improves when failed requests are excluded from the denominator.',response:1},
{key:2,source:'trace',truth:'The global success metric masks a slow booking path in one region; riders abandon before confirmation.',data:'Global 5xx 0.03%; East-region booking p95 8s; completed requests there down 22%.',people:'Riders in the East report a spinner and book with a competitor.',trace:'200 OK returned after 8s. Current availability SLI counts these as successful.',constraint:'Edge timing and region dimensions are already available.',risk:'The new latency average looks healthy while p99 remains 12 seconds.',response:1}],
['State a measurable customer outcome, not only engagement volume.','Include direct, proxy, balancing and technical indicators.','Define good events over eligible events, with a window and exclusions.']),
make('reliability','Reliability & incidents','Make SLOs useful under pressure.','Parcel · incident command',
'Delivery confirmation is failing and enterprise customers are escalating. You own incident coordination. Choose the first response, then define the SLI, SLO, SLA implications and postmortem.',
['SLI, SLO, error budget and SLA distinction','Immediate mitigation and incident roles','Customer communication and update cadence','Blameless timeline and prevention owners'],
['Roll back the latest release and verify recovery','Fail over the regional dependency and shed optional load','Promise 100% uptime and wait for diagnosis'],[
{key:0,source:'trace',truth:'The incident began immediately after a serializer change. Infrastructure is healthy and the previous release is compatible.',data:'Bad confirmations 9% since 14:05; target 99.9% over 30 days; 100,000 eligible events today.',people:'Support needs an acknowledgement and next-update time, not an unverified ETA.',trace:'14:04 deploy v42; 14:05 deserialization errors. v41 uses the current compatible schema.',constraint:'Rollback takes 3 minutes. Migration is backward-compatible.',risk:'Rollback restores service, but duplicate confirmations need reconciliation.',response:0},
{key:1,source:'trace',truth:'A regional dependency is timing out. There was no application deployment; a tested secondary region is healthy.',data:'Primary provider timeout 24%; secondary 0.1%; no app version change in 3 days.',people:'Enterprise customers ask whether their delivery records are lost.',trace:'All failures originate in primary-region storage; replication lag 4 seconds.',constraint:'Failover runbook was tested last week. Optional reports can be suspended.',risk:'Failover restores writes but a four-second replication gap affects some records.',response:0}],
['Calculate an event-based error budget consistently with the chosen SLI.','Mitigate before assigning cause, and communicate uncertainty.','Write a blameless postmortem with owners, due dates and verification.']),
make('quality','Product quality & testing','Turn risks into release criteria.','Velo · fare launch',
'A new fare experience is scheduled for Friday. QA asks which test investment must gate launch. Write acceptance criteria and a risk-based coverage plan.',
['Given/When/Then acceptance criteria','Functional, contract and regression coverage','Non-functional tests and representative workload','Release gates, canary and rollback criteria'],
['Gate on pricing boundary and contract tests','Gate on peak-load and degradation tests','Launch after the happy-path demo passes'],[
{key:0,source:'support',truth:'The calculation rounds at the wrong boundary when crossing midnight or changing currency.',data:'Peak-load latency remains below target; 2.1% of cross-midnight fares are incorrect.',people:'QA reproduces the error at 23:59 and with three-decimal currency amounts.',trace:'Calculation rounds each segment before summing; spec requires rounding the final total.',constraint:'A deterministic fixture suite can be added today.',risk:'A coupon stacked with a currency conversion reveals another rounding edge.',response:0},
{key:1,source:'analytics',truth:'Pricing correctness tests pass, but the new service saturates at expected Friday load.',data:'p95 250ms at 100rps; 6s at 700rps; Friday forecast 900rps.',people:'QA only tested one user. Operations has a realistic traffic replay.',trace:'Connection pool saturation leads to retry amplification under load.',constraint:'Staging can replay anonymized traffic; launch can be canaried.',risk:'A canary passes at low volume, but a region sees a synchronized surge.',response:0}],
['Test boundaries and negative paths, not just the demonstration.','Tie load, security and resilience tests to realistic risk.','State measurable acceptance and rollback criteria.']),
make('security','Security, privacy & fraud','Protect users without ignoring product friction.','Parcel · trust and safety',
'The business sees rising loss and customers question how their data is used. Prioritize the first control and document a threat model, privacy safeguards and fraud guardrails.',
['Assets, actors, trust boundaries and abuse cases','API authorization and layered controls','PII inventory, purpose, retention and deletion','Fraud signals, false positives and review/appeal'],
['Enforce object-level authorization and audit access','Add velocity checks with step-up verification and appeals','Collect more personal data from every user indefinitely'],[
{key:0,source:'trace',truth:'Authenticated users can enumerate other customers’ order details by changing the order ID.',data:'Refund loss stable; 73 sequential order reads by one account in 2 minutes.',people:'A customer received another person’s delivery address from the order endpoint.',trace:'GET /orders/other-user-id returns 200. Handler checks login but not order ownership.',constraint:'Ownership is present in the database; logs must avoid full addresses.',risk:'A bulk export endpoint bypasses the new single-order authorization check.',response:0},
{key:1,source:'analytics',truth:'Authorization checks pass. A coordinated refund ring exploits repeat claims across new accounts.',data:'Refund loss 4.2% vs 0.6% baseline; 81% of excess claims share device and payment patterns.',people:'Legitimate customers fear blanket refund blocks. Review capacity is limited.',trace:'Cross-account order reads return 403. Refund rate limits are absent.',constraint:'Risk signals must be minimized and retention bounded; offer human review.',risk:'A shared university network triggers false positives for legitimate users.',response:1}],
['Separate authentication, object authorization and abuse prevention.','Minimize PII and specify retention/deletion and access controls.','Measure false positives and provide an appeal; legal obligations need qualified review.']),
make('prd','Complexity & PRD writing','Make scope, dependencies and uncertainty explicit.','Velo · scooter expansion',
'The CEO wants to launch scooter rentals. Turn the idea into a scoped PRD and estimate complexity at company, service and feature levels.',
['Problem, audience, success criteria and non-goals','Requirements and testable acceptance criteria','Architecture, dependencies and risk register','Complexity ranges, milestones and discovery plan'],
['Run a hardware and operations feasibility pilot first','Ship a narrow software pilot on the proven fleet platform','Commit to a city-wide launch date before discovery'],[
{key:0,source:'support',truth:'No one has validated locks, battery telemetry, charging operations or city operating permission.',data:'Zero operational scooters; target 1,000 vehicles; unit economics are a spreadsheet assumption.',people:'Operations has no charging partner. Hardware team has only a prototype lock.',trace:'Lock API emulator works, but no physical device integration has run.',constraint:'A 20-scooter feasibility pilot fits the discovery budget.',risk:'Field tests reveal 8% of locks fail in rain.',response:0},
{key:1,source:'support',truth:'An acquired fleet already runs reliable hardware and operations. The missing piece is an in-app rental flow.',data:'Existing 800-scooter fleet: 99.5% unlock success and known contribution margin.',people:'Operations and local permissions are already in place; users need account linking.',trace:'Production lock API and telemetry have versioned contracts and a sandbox.',constraint:'Existing fleet can support a 50-user gated software pilot.',risk:'Account linking fails for customers with legacy phone numbers.',response:0}],
['Separate company, service and feature complexity.','Use ranges and dependencies rather than unsupported precision.','Specify non-goals, rollout, acceptance and discovery exit criteria.']),
make('capstone','Tech PM capstone','Own the launch of a music-streaming service.','Amplitude · music streaming',
'The CEO wants an independent music-streaming product. Take it from discovery through launch: architecture, API and stack, metric tree, trust and reliability, then a scoped PRD. Feedback is held until your final submission.',
['Service blueprint and architecture','API, client stack and offline behavior','Metric tree, SLIs and SLOs','Quality, privacy, rights and incident plan','PRD, complexity and phased roadmap'],
['Pilot streaming with licensed catalog and measured quality gates','Prioritize offline downloads and rights enforcement','Launch globally with all features immediately'],[
{key:0,source:'support',truth:'The launch audience streams on reliable Wi-Fi. Distribution rights cover one country and prohibit offline storage.',data:'Pilot users: 94% Wi-Fi listening; 87% want catalog discovery; offline demand 4%.',people:'Label counsel confirms streaming-only rights in one country. Creator onboarding is ready.',trace:'Playback service supports signed, short-lived streaming URLs. No offline license endpoint.',constraint:'Five engineers, eight weeks; one-country rights agreement signed.',risk:'A launch partner asks for worldwide access before rights are expanded.',response:1},
{key:1,source:'support',truth:'The audience commutes through poor coverage and the signed agreement explicitly permits expiring offline licenses.',data:'46% of sessions lose connectivity; streaming-only retention in this cohort is 18%.',people:'Listeners want offline commute playback. Rights holders require license expiry and revocation.',trace:'Provider offers encrypted downloads and 48-hour license expiry.',constraint:'Mobile engineers are available; the pilot can be limited to one country.',risk:'A revoked track remains in a device cache after the offline license expires.',response:0}],
['Carry one coherent set of constraints through every deliverable.','Connect architecture to rights, user needs, cost and reliability.','Defend sequencing and define the evidence that would reverse the decision.'])
];

export const sources = [
{id:'analytics',name:'Analytics console',kind:'Data',cost:2,description:'Inspect segmented usage and operational metrics.'},
{id:'support',name:'Stakeholder interviews',kind:'People',cost:2,description:'Talk to customers, operations and domain experts.'},
{id:'trace',name:'Service traces',kind:'Systems',cost:2,description:'Inspect requests, failure paths and dependencies.'},
{id:'constraints',name:'Planning brief',kind:'Context',cost:1,description:'Check capacity, existing capabilities and deadlines.'}
];

export const capstoneStages = [
{title:'Frame the launch',prompt:'Choose the product direction using the rights and audience evidence.',options:null},
{title:'Architecture & API',prompt:'Choose a delivery architecture consistent with your audience and rights.',options:['Signed streaming URLs with regional access checks','Encrypted offline media with expiring licenses','Public permanent URLs for every track']},
{title:'Metric tree',prompt:'Choose a primary launch quality measure with a customer outcome.',options:['Successful playback starts within 2 seconds, with retained listeners as an outcome','Successful licensed offline plays, with retained commuters as an outcome','Total downloads of the app']},
{title:'Trust & reliability',prompt:'Choose the release control that addresses the dominant product risk.',options:['Region-rights enforcement with playback canary and rollback','Expiry/revocation tests with offline recovery and staged rollout','Skip rights checks to reduce playback latency']},
{title:'PRD & complexity',prompt:'Commit to a scoped roadmap and defend what you defer.',options:['One-country streaming pilot before discovery and catalog expansion','One-country offline pilot before broader device and catalog expansion','Global launch, social feed and podcasts in the first sprint']}
];
